name: Test Sample Data

on: [push, pull_request, check_run]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    env:
        PACKAGES: "pytest flake8"
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.7]
        os: [ubuntu-16.04, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: python3 -m pip install --upgrade pip setuptools nose
    - name: Validate sample data
      run: make validate_sampledata
